import * as dotenv from "dotenv";

dotenv.config();
export const {
  ADMIN_SECRET_KEY,
  CUSTOMER_SECRET_KEY,
  USER_SECRET_KEY,
  SES_AWS_ACCESS_KEY_ID,
  SES_AWS_SECRET_ACCESS_KEY,
  SES_REGION,
  SES_AWS_SMTP_SENDER,
  URL_AMIN,
  URL_CUSTOMER,
  S3_BUCKET,
  ENV,
  IS_PRODUCTION,
  API_KEY_GOOGLE_MAP,
  API_WEBHOOK_TOKEN_PAYJP,
  CUSTOMER_CONFIRM_MAIL_SECRET_KEY,
  SECRET_KEY_PAYJP,
  SECRET_KEY_STRIPE,
  API_WEBHOOK_TOKEN_STRIPE,
} = process.env;